name: Scrape Combined Hotel Rates

# Triggers: nightly at 02:00 UTC, or manual dispatch
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Python 3.x
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install your requirements
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Run the combined scraper
      - name: Run combined scraper
        env:
          SERPAPI_KEY:     ${{ secrets.SERPAPI_KEY }}
          RAPIDAI_API_KEY: ${{ secrets.RAPIDAI_API_KEY }}
        run: python scrape_combined_rates.py
