name: Daily Hotel Rate Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # every day at 12:00 UTC (8am EST)

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run hotel rate scraper
      run: python scrape_hotels.py

    - name: Commit and push updated data
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/beckley_rates.json
        git commit -m "Update Beckley hotel rates"
        git push
      env:
        # Needed so GitHub can push on your behalf
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
