name: Scrape Beckley Rates

on:
  schedule:
    # every day at 09:00 UTC (adjust to your preferred time)
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      SERPAPI_KEY:     ${{ secrets.SERPAPI_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}  # ← was RAPIDAI_API_KEY

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_combined_rates.py

      - name: Commit updated rates JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/beckley_rates.json
          git commit -m "Auto-update hotel rates"
          git push
