name: Daily Hotel Rate Scraper

on:
  workflow_dispatch:  # <-- allows manual triggering
  schedule:
    - cron: "0 9 * * *"  # runs every day at 9:00 AM UTC (adjust if needed)

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run hotel rate scraper
        run: python scrape_hotels.py
