name: Scrape Combined Hotel Rates

on:
  # run nightly at 02:00 UTC
  schedule:
    - cron: '0 2 * * *'
  # or manually start from the Actions UI
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ List everything in the workspace so we can confirm paths
      - name: List workspace contents
        run: |
          echo "Working directory: $PWD"
          ls -R .

      # 3️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      # 5️⃣ Run your scraper
      - name: Run combined scraper
        env:
          SERPAPI_KEY:    ${{ secrets.SERPAPI_KEY }}
          RAPIDAI_API_KEY: ${{ secrets.RAPIDAI_API_KEY }}
        run: |
          python scrape_combined_rates.py
