name: Scrape Beckley Rates

on:
  schedule:
    # every day at 09:00 UTC (adjust as desired)
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run combined scraper
        env:
          SERPAPI_KEY:        ${{ secrets.SERPAPI_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python scrape_combined_rates.py

      - name: Commit updated rates JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/beckley_rates.json
          git commit -m "Auto-update beckley_rates.json"
          git push
