name: Beckley Competitor Rate Tracker

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 UTC
  workflow_dispatch:       # Manual trigger allowed

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List workspace contents (debug)
        run: |
          echo "Current Directory: $PWD"
          ls -R .

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run combined scraper
        env:
          SERPAPI_KEY:     ${{ secrets.SERPAPI_KEY }}
          RAPIDAI_API_KEY: ${{ secrets.RAPIDAI_API_KEY }}
        run: |
          echo "DEBUG: SERPAPI_KEY is ${{ secrets.SERPAPI_KEY }}"  # Debug print
          python scrape_combined_rates.py
